### ISSUE TITLE
[Bug]: Rendering startup crash

### ISSUE THREAD

**Issue by StrangerSon71** [TeamLapen/Werewolves#106]
### Minecraft Version

1.18.x

### Forge Version

40.1.25

### Vampirism Version

1.8.2

### Werewolves Version

0.6.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

The game crashed while rendering overlay
No model for layer werewolves:ears_claws#main.
I believe this is an incompatibility, but I don't know with what.

### Relevant log output

```bash
https://pastebin.com/dRVv8DJj
```

**Comment by StrangerSon71** [comment]
Ok ElementalCraft seems to cause it.
Edit: Werewolves gives a startup crash referencing Werewolves when another mod is missing dependencies, very annoying for debug. Different error than above. I will attempt to narrow down the incompatibility once this is fixed.

**Comment by Cheaterpaul** [comment]
Yes it is a bug in Forge that shows Werewolves as error instead of the missing dependencies #96. This is known but i can't do much about it.

I got reports of the `werewolves:ears_claws#main` error before, but i could never determine the cause or reproduce the issue myself. For some the issue just resolved itself somehow. I appreciate your help in narrowing down the issue.

**Comment by Cheaterpaul** [comment]
I presume this issue does no longer occur with the latest Forge/Werewolves version

**Comment by EnderMelody** [comment]
still getting this error on 0.6.1, forge 40.1.68

**Comment by Cheaterpaul** [comment]
then please provide your debug.log file

**Comment by EnderMelody** [comment]
Crashlog:
[crash-2022-07-20_21.55.57-client.txt](https://github.com/TeamLapen/Werewolves/files/9162776/crash-2022-07-20_21.55.57-client.txt)
the actual crash was being caused by sophisticated backpacks/core but forge was blaming werewolves for the crash.

**Comment by EnderMelody** [comment]
started getting this randomly again. nothing changed in the modpack, just refused to start with werewolves installed. No other errors once the mod was removed.
[debug.log](https://github.com/TeamLapen/Werewolves/files/9302480/debug.log)

**Comment by Cheaterpaul** [comment]
The issue lies with TConstruct at line 17630 please try it without TConstruct and report it there

```bash
[10Aug2022 12:59:56.318] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block_entity_type> dispatch for modid tconstruct
java.lang.NullPointerException: Registry Object not present: tconstruct:scorched_fuel_tank
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:320) ~[forge-1.18.2-40.1.68-universal.jar%23424!/:?]
	at slimeknights.mantle.registration.object.ItemObject.get(ItemObject.java:63) ~[Mantle-1.18.2-1.9.27.jar%23262!/:1.18.2-1.9.27]
	at slimeknights.mantle.registration.object.ItemObject.get(ItemObject.java:21) ~[Mantle-1.18.2-1.9.27.jar%23262!/:1.18.2-1.9.27]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at slimeknights.mantle.registration.object.EnumObject.values(EnumObject.java:92) ~[Mantle-1.18.2-1.9.27.jar%23262!/:1.18.2-1.9.27]
	at slimeknights.tconstruct.smeltery.TinkerSmeltery.lambda$static$52(TinkerSmeltery.java:252) ~[TConstruct-1.18.2-3.5.1.31.jar%23375!/:1.18.2-3.5.1.31]
	at slimeknights.mantle.registration.deferred.BlockEntityTypeDeferredRegister.lambda$register$2(BlockEntityTypeDeferredRegister.java:75) ~[Mantle-1.18.2-1.9.27.jar%23262!/:1.18.2-1.9.27]
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:214) ~[forge-1.18.2-40.1.68-universal.jar%23424!/:?]
```

**Comment by EnderMelody** [comment]
the problem is, i removed werewolves and launched the pack to title fine, then readded it and it launches fine again. the crash seems to be random but once you get it you have to load the pack without werewolves to solve it. and it can happen without you changing anything in the pack.
