### ISSUE TITLE
[Bug]: Crash - ticking block entity werewolves:stone_altar

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Werewolves#155]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.8

### Werewolves Version

1.1.0.2

### Modpack

Vampirism.co

### Singleplayer/Multiplayer

Server

### What happened?

server crash, assumed to have happened after a player interacted with werewolves:stone_altar

### Relevant log output

```bash
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/23/23, 1:58 AM
Description: Ticking block entity

java.lang.IllegalStateException: Cannot get FactionPlayerHandler from EntityPlayer ServerPlayerEntity['...'/1055641, l='ServerLevel[world]', x=..., y=..., z=...](TextComponent{text='...', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at ...)
	at de.teamlapen.vampirism.entity.factions.FactionPlayerHandler.lambda$get$0(FactionPlayerHandler.java:66) ~[vampirism:1.9.8] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:285) ~[forge:?] {re:mixin,re:classloading}
	at de.teamlapen.vampirism.entity.factions.FactionPlayerHandler.get(FactionPlayerHandler.java:66) ~[vampirism:1.9.8] {re:classloading}
	at de.teamlapen.werewolves.blocks.entity.StoneAltarTileEntity.endRitual(StoneAltarTileEntity.java:178) ~[werewolves:1.1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.blocks.entity.StoneAltarTileEntity.func_73660_a(StoneAltarTileEntity.java:107) ~[werewolves:1.1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217391_K(World.java:670) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:543) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1089) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1002) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:817) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.teamlapen.vampirism.entity.factions.FactionPlayerHandler.lambda$get$0(FactionPlayerHandler.java:66) ~[vampirism:1.9.8] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:285) ~[forge:?] {re:mixin,re:classloading}
	at de.teamlapen.vampirism.entity.factions.FactionPlayerHandler.get(FactionPlayerHandler.java:66) ~[vampirism:1.9.8] {re:classloading}
	at de.teamlapen.werewolves.blocks.entity.StoneAltarTileEntity.endRitual(StoneAltarTileEntity.java:178) ~[werewolves:1.1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.blocks.entity.StoneAltarTileEntity.func_73660_a(StoneAltarTileEntity.java:107) ~[werewolves:1.1.0.2] {re:classloading,pl:runtimedistcleaner:A}
-- Block entity being ticked --
Details:
	Name: werewolves:stone_altar // de.teamlapen.werewolves.blocks.entity.StoneAltarTileEntity
	Block: Block{werewolves:stone_altar}[facing=east,lit=false,soulfire=false,waterlogged=false]
	Block location: World: (...), Chunk: (at ... in ...; contains blocks ... to ...), Region: (...; contains chunks ... to ..., blocks ... to ...)
	Block: Block{werewolves:stone_altar}[facing=east,lit=false,soulfire=false,waterlogged=false]
	Block location: World: (...), Chunk: (at ... in ...; contains blocks ... to ...), Region: (...; contains chunks ... to ..., blocks ... to ...)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:670) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:543) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by Cheaterpaul** [comment]
fixed in Werewolves 1.1.0.3
