### ISSUE TITLE
crash: Mixin class: de.teamlapen.werewolves

### ISSUE THREAD

**Issue by OBS3SS1ON** [TeamLapen/Werewolves#196]
### Minecraft Version

1.16.x

### Forge Version

forge-1.20.1-47.2.32

### Vampirism Version

Vampirism-1.20.1-1.10.7

### Werewolves Version

Werewolves-1.20.1-2.0.2.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

crash
[debug.log](https://github.com/user-attachments/files/15520033/debug.log)
[latest.log](https://github.com/user-attachments/files/15520034/latest.log)

**Comment by Cheaterpaul** [comment]
This is caused by WizardsReborn.

```
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at mod.maxbogomol.wizards_reborn.WizardsRebornClient.<clinit>(WizardsRebornClient.java:127) ~[wizards_reborn-1.20.1-0.1.2.jar%23926!/:1.20.1-0.1.2]
	at net.minecraft.client.gui.screens.TitleScreen.handler$fci001$render(TitleScreen.java:2019) ~[client-1.20.1-20230612.114412-srg.jar%23942!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_88315_(TitleScreen.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23942!/:?]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23942!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.32-universal.jar%23947!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.32-universal.jar%23947!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23942!/:?]
```
