### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by Lukebb04** [TeamLapen/Werewolves#207]
### Minecraft Version

1.21.x

### Forge Version

21.1.23

### Vampirism Version

1.10.0-beta.1

### Werewolves Version

2.0.2.3-alpha240822-1958

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I killed a werewolf then I crashed

### Relevant log output

```bash
java.lang.StackOverflowError: Unexpected error
	at TRANSFORMER/werewolves@2.0.2.3-alpha240822-1958/de.teamlapen.werewolves.api.entities.werewolf.WerewolfForm.getSize(WerewolfForm.java:77) ~[Werewolves-1.21-2.0.2.3-alpha240822-1958.jar%23185!/:1.21-2.0.2.3-alpha240822-1958] {re:mixin,re:classloading}
	at TRANSFORMER/werewolves@2.0.2.3-alpha240822-1958/de.teamlapen.werewolves.entities.werewolf.BasicWerewolfEntity.getDefaultDimensions(BasicWerewolfEntity.java:108) ~[Werewolves-1.21-2.0.2.3-alpha240822-1958.jar%23185!/:1.21-2.0.2.3-alpha240822-1958] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.getDimensions(LivingEntity.java:3344) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity from mod vampirism,pl:mixin:APP:vampirism.mixins.json:accessor.LivingEntityAccessor from mod vampirism,pl:mixin:APP:werewolves.mixins.json:LivingEntityAccessor from mod werewolves,pl:mixin:APP:werewolves.mixins.json:entity.LivingEntityMixin from mod werewolves,pl:mixin:A}
```

### Reproduce steps

1. Kill a werewolf
2. Crash

**Comment by Cheaterpaul** [comment]
fixed in the latest version
