### ISSUE TITLE
[Bug]: game cannon finish loading

### ISSUE THREAD

**Issue by kodamant** [TeamLapen/Werewolves#208]
### Minecraft Version

1.21.x

### Forge Version

neoforge 21.0.167

### Vampirism Version

1.10.0 beta2

### Werewolves Version

2.0.2.3 alpha

### Singleplayer/Multiplayer

Singleplayer

### What happened?

game successfully loads, but the loading splash screen remains stuck at the very end, menu music plays, yet the screen never leaves, using a mod that changes the splash screen allows button navigation, but then the game crashes upon attempting to load a world or join a server. this occurs even in a vacuum of just vampirism and werewolves, on a brand new installation

### Relevant log output

```bash
null[28Aug2024 19:44:15.083] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, {MINECRAFT_USERNAME}, --version, 1.21, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\testing, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\meta\assets, --assetIndex, 17, --uuid, {MINECRAFT_UUID}, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480, --fml.neoForgeVersion, 21.0.167, --fml.fmlVersion, 4.0.23, --fml.mcVersion, 1.21, --fml.neoFormVersion, 20240613.152323, --launchTarget, forgeclient]
[28Aug2024 19:44:15.089] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Azul Systems, Inc. OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[28Aug2024 19:44:15.091] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.3 by Azul Systems, Inc.; OS Windows 10 arch amd64 version 10.0
[28Aug2024 19:44:15.275] [main/WARN] [net.neoforged.fml.loading.FMLConfig/CORE]: Configuration file C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\testing\config\fml.toml is not correct. Correcting
[28Aug2024 19:44:15.277] [main/INFO] [net.neoforged.fml.loading.FMLConfig/CORE]: Incorrect key [disableConfigWatcher] was corrected from null to false
[28Aug2024 19:44:15.279] [main/INFO] [net.neoforged.fml.loading.FMLConfig/CORE]: Incorrect key [earlyWindowSkipGLVersions] was corrected from null to []
[28Aug2024 19:44:15.279] [main/INFO] [net.neoforged.fml.loading.FMLConfig/CORE]: Incorrect key [earlyWindowSquir] was corrected from null to false
[28Aug2024 19:44:15.333] [main/INFO] [net.neoforged.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[28Aug2024 19:44:15.554] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[28Aug2024 19:44:15.699] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[28Aug2024 19:44:15.878] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.6 Source=union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/ModrinthApp/meta/libraries/net/fabricmc/sponge-mixin/0.14.0+mixin.0.8.6/sponge-mixin-0.14.0+mixin.0.8.6.jar%23124!/ Service=ModLauncher Env=CLIENT
[28Aug2024 19:44:16.317] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon RX 5500 GL version 4.6.0 Core Profile Context 24.7.1.240711, ATI Technologies Inc.
[28Aug2024 19:44:16.640] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "client-1.21-20240613.152323-srg.jar" [locator: production client provider +net.neoforged:neoforge:21.0.167:client]
[28Aug2024 19:44:16.670] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-21.0.167-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\meta\libraries\net\neoforged\neoforge\21.0.167\neoforge-21.0.167-universal.jar]], reader: mod manifest]
[28Aug2024 19:44:16.700] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Vampirism-1.21-1.10.0-beta.2.jar" [locator: {mods folder locator at C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\testing\mods}, reader: mod manifest]
[28Aug2024 19:44:16.712] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Werewolves-1.21-2.0.2.3-alpha240822-1958.jar" [locator: {mods folder locator at C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\testing\mods}, reader: mod manifest]
[28Aug2024 19:44:16.892] [main/INFO] [net.neoforged.fml.loading.moddiscovery.locators.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[28Aug2024 19:44:16.892] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found gamelibrary file "mixinextras-neoforge-0.3.5.jar" [parent: neoforge-21.0.167-universal.jar, locator: jarinjar, reader: mod manifest]
[28Aug2024 19:44:17.178] [main/INFO] [net.neoforged.fml.loading.FMLServiceProvider/CORE]: Loading coremod script-engine for [neoforge]
[28Aug2024 19:44:18.549] [main/INFO] [mixin/]: Compatibility level set to JAVA_21
[28Aug2024 19:44:18.567] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.21, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\profiles\testing, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\ModrinthApp\meta\assets, --uuid, {MINECRAFT_UUID}, --username, {MINECRAFT_USERNAME}, --assetIndex, 17, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480]
[28Aug2024 19:44:19.874] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[28Aug2024 19:44:22.315] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 229 Datafixer optimizations took 746 milliseconds
[28Aug2024 19:44:22.498] [main/WARN] [oshi.driver.windows.perfmon.PerfmonDisabled/]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[28Aug2024 19:44:24.652] [pool-8-thread-1/WARN] [mixin/]: Method overwrite conflict for getHiddenEffect in werewolves.mixins.json:MobEffectInstanceAccessor from mod werewolves, previously written by de.teamlapen.vampirism.mixin.MixinMobEffectInstance. Skipping method.
[28Aug2024 19:44:31.063] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/ModrinthApp/meta/libraries/net/minecraft/client/1.21-20240613.152323/client-1.21-20240613.152323-srg.jar%23182!/assets/.mcassetsroot' uses unexpected schema
[28Aug2024 19:44:31.064] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/ModrinthApp/meta/libraries/net/minecraft/client/1.21-20240613.152323/client-1.21-20240613.152323-srg.jar%23182!/data/.mcassetsroot' uses unexpected schema
[28Aug2024 19:44:31.097] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[28Aug2024 19:44:31.112] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: {MINECRAFT_USERNAME}
[28Aug2024 19:44:31.222] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.3+5
[28Aug2024 19:44:31.639] [modloading-worker-0/INFO] [net.neoforged.neoforge.common.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.0.167, for MC 1.21
[28Aug2024 19:44:40.672] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: vanilla, mod_resources, mod/vampirism,teamlapenlib, mod/neoforge, mod/werewolves
[28Aug2024 19:44:40.693] [Forge Version Check/INFO] [net.neoforged.fml.VersionChecker/]: [werewolves] Starting version check at https://api.modrinth.com/updates/werewolves/forge_updates.json
[28Aug2024 19:44:40.834] [Worker-Main-3/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_all_no_pua-15.1.05.hex, loading
[28Aug2024 19:44:40.948] [Worker-Main-4/ERROR] [net.minecraft.Util/]: Invalid path in pack: vampirism:sounds/reserved/LICENSE.txt, ignoring
[28Aug2024 19:44:40.949] [Worker-Main-4/ERROR] [net.minecraft.Util/]: Invalid path in pack: vampirism:sounds/cc/LICENSE.txt, ignoring
[28Aug2024 19:44:41.023] [Forge Version Check/INFO] [net.neoforged.fml.VersionChecker/]: [werewolves] Found status: BETA Current: 2.0.2.3-alpha240822-1958 Target: null
[28Aug2024 19:44:41.024] [Forge Version Check/INFO] [net.neoforged.fml.VersionChecker/]: [vampirism] Starting version check at https://api.modrinth.com/updates/vampirism/forge_updates.json
[28Aug2024 19:44:41.111] [Forge Version Check/INFO] [net.neoforged.fml.VersionChecker/]: [vampirism] Found status: BETA Current: 1.10.0-beta.2 Target: null
[28Aug2024 19:44:41.429] [Worker-Main-4/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_jp_patch-15.1.05.hex, loading
[28Aug2024 19:44:44.572] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[28Aug2024 19:44:44.573] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[28Aug2024 19:44:44.714] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on Speakers (Razer Kraken V3 X)
[28Aug2024 19:44:44.716] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[28Aug2024 19:44:44.922] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[28Aug2024 19:44:44.951] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[28Aug2024 19:44:44.953] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[28Aug2024 19:44:44.965] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[28Aug2024 19:44:44.974] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[28Aug2024 19:44:44.998] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[28Aug2024 19:44:44.999] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[28Aug2024 19:44:44.999] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[28Aug2024 19:44:44.999] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[28Aug2024 19:44:45.117] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'org.apache.commons.lang3.tuple.Pair[] de.teamlapen.werewolves.client.render.HumanWerewolfRenderer.separateSlimTextures(java.util.stream.Stream)'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%23117!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%23117!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%23117!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%23117!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23112!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
Caused by: java.lang.NoSuchMethodError: 'org.apache.commons.lang3.tuple.Pair[] de.teamlapen.werewolves.client.render.HumanWerewolfRenderer.separateSlimTextures(java.util.stream.Stream)'
	at TRANSFORMER/werewolves@2.0.2.3-alpha240822-1958/de.teamlapen.werewolves.client.render.HumanWerewolfRenderer.gatherTextures(HumanWerewolfRenderer.java:36) ~[Werewolves-1.21-2.0.2.3-alpha240822-1958.jar%23185!/:1.21-2.0.2.3-alpha240822-1958]
	at TRANSFORMER/werewolves@2.0.2.3-alpha240822-1958/de.teamlapen.werewolves.client.render.HumanWerewolfRenderer.<init>(HumanWerewolfRenderer.java:26) ~[Werewolves-1.21-2.0.2.3-alpha240822-1958.jar%23185!/:1.21-2.0.2.3-alpha240822-1958]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.entity.EntityRenderers.lambda$createEntityRenderers$26(EntityRenderers.java:168) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar%23114!/:?]
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1004) ~[fastutil-8.5.12.jar%23114!/:?]
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar%23114!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.entity.EntityRenderers.createEntityRenderers(EntityRenderers.java:166) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.entity.EntityRenderDispatcher.onResourceManagerReload(EntityRenderDispatcher.java:479) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:15) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
	... 25 more
[28Aug2024 19:44:45.140] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: vanilla, mod_resources, mod/vampirism,teamlapenlib, mod/neoforge, mod/werewolves
[28Aug2024 19:44:45.147] [Worker-Main-6/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_all_no_pua-15.1.05.hex, loading
[28Aug2024 19:44:45.199] [Worker-Main-5/ERROR] [net.minecraft.Util/]: Invalid path in pack: vampirism:sounds/reserved/LICENSE.txt, ignoring
[28Aug2024 19:44:45.200] [Worker-Main-5/ERROR] [net.minecraft.Util/]: Invalid path in pack: vampirism:sounds/cc/LICENSE.txt, ignoring
[28Aug2024 19:44:45.540] [Worker-Main-7/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_jp_patch-15.1.05.hex, loading
[28Aug2024 19:44:47.393] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[28Aug2024 19:44:47.394] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[28Aug2024 19:44:47.472] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on Speakers (Razer Kraken V3 X)
[28Aug2024 19:44:47.472] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[28Aug2024 19:44:47.562] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[28Aug2024 19:44:47.587] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[28Aug2024 19:44:47.589] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[28Aug2024 19:44:47.600] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[28Aug2024 19:44:47.609] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[28Aug2024 19:44:47.633] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[28Aug2024 19:44:47.634] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[28Aug2024 19:44:47.635] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[28Aug2024 19:44:47.635] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
```

### Reproduce steps

step one: attempt to launch the game
step two: profit.

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Lukebb04** [comment]
same as https://github.com/TeamLapen/Werewolves/issues/206

**Comment by Cheaterpaul** [comment]
should be fixed by the newest alpha version
