### ISSUE TITLE
[Bug] AbstractMethodError ITotem#getWorld

### ISSUE THREAD

**Issue by arch-atlas** [TeamLapen/Werewolves#30]
## Versions
- Minecraft:1.16                   
- Forge: latest                      
- Vampirism: 1.7.0 (latest)
- Werewolves: 1.0.0 (latest)

- ModPack: N/A

## Issue Description
game crashes upon trying to capture village totem

## Reproduce Steps
right click on a totem while in a faction and it should either crash immediately or after there are no defenders left

## Additional Information

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 12/14/20 9:58 PM
Description: Ticking block entity

java.lang.AbstractMethodError: Method de/teamlapen/vampirism/tileentity/TotemTileEntity.getWorld()Lnet/minecraft/world/World; is abstract
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.getWorld(TotemTileEntity.java) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.api.event.VampirismVillageEvent.getWorld(VampirismVillageEvent.java:53) ~[?:1.7.0] {re:classloading,pl:eventbus:A}
	at de.teamlapen.werewolves.world.WWorldEventHandler.onVillageCaptureFinish(WWorldEventHandler.java:22) ~[?:1.0.0-alpha+20201212-0053] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_137_WWorldEventHandler_onVillageCaptureFinish_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at de.teamlapen.vampirism.util.ModEventFactory.fireVillagerCaptureEventPre(ModEventFactory.java:23) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.updateCreaturesOnCapture(TotemTileEntity.java:875) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.completeCapture(TotemTileEntity.java:244) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.func_73660_a(TotemTileEntity.java:448) ~[?:1.7.0] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5811/663139908.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.getWorld(TotemTileEntity.java) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.api.event.VampirismVillageEvent.getWorld(VampirismVillageEvent.java:53) ~[?:1.7.0] {re:classloading,pl:eventbus:A}
	at de.teamlapen.werewolves.world.WWorldEventHandler.onVillageCaptureFinish(WWorldEventHandler.java:22) ~[?:1.0.0-alpha+20201212-0053] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_137_WWorldEventHandler_onVillageCaptureFinish_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at de.teamlapen.vampirism.util.ModEventFactory.fireVillagerCaptureEventPre(ModEventFactory.java:23) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.updateCreaturesOnCapture(TotemTileEntity.java:875) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.completeCapture(TotemTileEntity.java:244) ~[?:1.7.0] {re:classloading}
	at de.teamlapen.vampirism.tileentity.TotemTileEntity.func_73660_a(TotemTileEntity.java:448) ~[?:1.7.0] {re:classloading}
-- Block entity being ticked --
Details:
	Name: vampirism:totem // de.teamlapen.vampirism.tileentity.TotemTileEntity
	Block: Block{werewolves:totem_top_werewolves_werewolf}
	Block location: World: (138,69,-1871), Chunk: (at 10,4,1 in 8,-117; contains blocks 128,0,-1872 to 143,255,-1857), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Block: Block{werewolves:totem_top_werewolves_werewolf}
	Block location: World: (138,69,-1871), Chunk: (at 10,4,1 in 8,-117; contains blocks 128,0,-1872 to 143,255,-1857), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading,pl:accesstransformer:B}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Atlas_05'/153, l='ServerLevel[Vampirism Survival]', x=140.81, y=67.94, z=-1871.95]]
	Chunk stats: ServerChunkCache: 2986
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,64,-224), Chunk: (at 0,4,0 in -14,-14; contains blocks -224,0,-224 to -209,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 33740 game time, 48411 day time
	Level name: Vampirism Survival
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 89663 (now: false), thunder time: 103007 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5811/663139908.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 636714944 bytes (607 MB) / 2425356288 bytes (2313 MB) up to 5189926912 bytes (4949 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5568m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.9.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.9.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.9
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.9-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.78-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.76     |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.9-universal.jar                 |Forge                         |forge                         |35.1.9              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Guide-API-VP-1.16.4-2.2.0.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.0               |DONE      |NOSIGNATURE
		Just+Sword+Blocking-1.16.3.jar                    |Just Sword Blocking           |justswordblocking             |1.0                 |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.0 (1).jar                    |Vampirism                     |vampirism                     |1.7.0               |DONE      |NOSIGNATURE
		Werewolves-1.16.4-1.0.0-alpha+20201212-0053.jar   |Werewolves                    |werewolves                    |1.0.0-alpha+20201212|DONE      |NOSIGNATURE
	Crash Report UUID: cc1dd5a8-1d04-479b-a89c-3d1bae63d06d
	Player Count: 1 / 8; [ServerPlayerEntity['Atlas_05'/153, l='ServerLevel[Vampirism Survival]', x=140.81, y=67.94, z=-1871.95]]
	Data Packs: vanilla, mod:sereneseasons, mod:forge, mod:guideapi-vp (incompatible), mod:justswordblocking, mod:jei, mod:vampirism (incompatible), mod:werewolves (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Cheaterpaul** [comment]
fixed 1.0.0-alpha+20201215-1717
