### ISSUE TITLE
[Bug] Crash on thirdperson rendering with Obfuscate installed

### ISSUE THREAD

**Issue by NE1W01F** [TeamLapen/Werewolves#39]
## Versions
- Minecraft:  1.16.4              
- Forge:  1.16.4-forge-35.1.4            
- Vampirism: Vampirism-1.16.4-1.7.7
- Werewolves: Werewolves-1.16.4-1.0.0-alpha+20210309-1957

- ModPack: N/A
- 
## Issue Description
Crashes when i press f5 in werewolf form. the error say thats its unable to cast to player entitly

## Reproduce Steps
1. get to the werewolf form
2. press f5
3. crash

## Additional Information
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 15/03/21 21:50
Description: Rendering entity in world

java.lang.ClassCastException: de.teamlapen.werewolves.client.model.WerewolfBeastModel cannot be cast to net.minecraft.client.renderer.entity.model.PlayerModel
	at com.mrcrayfish.obfuscate.client.Hooks.fireRenderPlayer(Hooks.java:42) ~[?:0.6.0-1.16.3] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.redirect$zzf000$fireRenderPlayer(LivingRenderer.java:541) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.render.WerewolfPlayerRenderer.render(WerewolfPlayerRenderer.java:93) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.render.WerewolfPlayerRenderer.render(WerewolfPlayerRenderer.java:75) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.core.ClientEventHandler.onRenderPlayer(ClientEventHandler.java:34) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_263_ClientEventHandler_onRenderPlayer_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:63) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1197) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1005) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/624637962.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.obfuscate.client.Hooks.fireRenderPlayer(Hooks.java:42) ~[?:0.6.0-1.16.3] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.redirect$zzf000$fireRenderPlayer(LivingRenderer.java:541) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.render.WerewolfPlayerRenderer.render(WerewolfPlayerRenderer.java:93) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.render.WerewolfPlayerRenderer.render(WerewolfPlayerRenderer.java:75) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.werewolves.client.core.ClientEventHandler.onRenderPlayer(ClientEventHandler.java:34) ~[?:1.0.0-alpha+20210309-1957] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_263_ClientEventHandler_onRenderPlayer_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:63) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 179
	Entity Name: NE1W01F
	Entity's Exact location: 109.48, 75.00, 68.86
	Entity's Block location: World: (109,75,68), Chunk: (at 13,4,4 in 6,4; contains blocks 96,0,64 to 111,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@5e0e97b6
	Location: -3.27,-3.59,1.31 - World: (-4,-4,1), Chunk: (at 12,-1,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -1371.8799
	Delta: 0.2600453
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1197) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1005) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['NE1W01F'/179, l='ClientLevel', x=109.48, y=75.00, z=68.86]]
	Chunk stats: Client Chunk Cache: 361, 219
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,63,38), Chunk: (at 0,3,6 in -3,2; contains blocks -48,0,32 to -33,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 150113 game time, 81075 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/624637962.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2882324048 bytes (2748 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.4
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.2.2.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.2.2               |DONE      |NOSIGNATURE
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		guardvillagers-1.16.4-1.1.10.jar                  |Guard Villagers               |guardvillagers                |1.1.10              |DONE      |NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.70.jar                           |Just Enough Items             |jei                           |7.6.1.70            |DONE      |NOSIGNATURE
		DoggyTalents-1.16.4-2.0.1.3.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.3             |DONE      |NOSIGNATURE
		SpawnEggRecipes+-+1.4.0+(Sheep+Bug+Fix)+(EASY+MODE|Spawn Egg Recipes Mod         |spawn                         |1.16.4-1.2.0        |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.4-universal.jar                 |Forge                         |forge                         |35.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		easy_villagers-1.16.4-1.1.29.jar                  |Easy Villagers                |easy_villagers                |1.16.4-1.1.29       |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.0.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.0               |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.7.7.jar                        |Vampirism                     |vampirism                     |1.7.7               |DONE      |NOSIGNATURE
		Werewolves-1.16.4-1.0.0-alpha+20210309-1957.jar   |Werewolves                    |werewolves                    |1.0.0-alpha+20210309|DONE      |NOSIGNATURE
		sisser-1.7.jar                                    |Sisser                        |sisser                        |1.7                 |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Neat+1.7-24.jar                                   |Neat                          |neat                          |1.7-24              |DONE      |NOSIGNATURE
		essentials-1.16.4-2.10.0.jar                      |Essentials                    |essentials                    |1.16.4-2.10.0       |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.4.2_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.4.2              |DONE      |NOSIGNATURE
		easy_piglins-1.16.4-1.0.5.jar                     |Easy Piglins                  |easy_piglins                  |1.16.4-1.0.5        |DONE      |NOSIGNATURE
	Crash Report UUID: 155749e3-0528-4f54-bbcb-7e0507cd63d7
	Patchouli open book context: n/a
	Launched Version: 1.16.4-forge-35.1.4
	Backend library: LWJGL version 3.2.2 build 10
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)

**Comment by Cheaterpaul** [comment]
Thanks for the detailed Issue

This is caused by Obfuscate
because the object is cast without checking

I already created an issue there MrCrayfish/Obfuscate#23 and an pull request is already suggested MrCrayfish/Obfuscate#5.
Unfortunately it does not seems like MrCrayfish has an interest in fixing this issue. So lets hope someday he does.

**Comment by Cheaterpaul** [comment]
I removed the compatibility because the workaround is incompatible with other mods.
Since there is no other way both mods with be incompatible together unless Obfuscate fixes this issue i cant do anything

**Comment by Cheaterpaul** [comment]
Both mods will be compatible with Obfucate 0.6.3

But this version will probably only be released for 1.17+

**Comment by SweetestBoy** [comment]
Will Obfucate 0.6.3 be released for 1.16.5?

**Comment by Cheaterpaul** [comment]
seem not, but the Werewolf 0.6 alpha versions are also compatible
