### ISSUE TITLE
[Bug]: java.lang.Throwable: null in Server Console when Player Dies

### ISSUE THREAD

**Issue by phillipinman** [TeamLapen/Werewolves#92]
### Minecraft Version

1.18.x

### Forge Version

40.1.0

### Vampirism Version

1.8.2-alpha+20220413-2209

### Werewolves Version

0.6.0-alpha+20220419-1840

### Modpack

Personal Pack

### Singleplayer/Multiplayer

Server

### What happened?

When a player dies the server outputs the following error (in log section)

Edit: This also occurs on player join to the server.

Reproduction of this issue appears to affect any player regardless if they are werewolf, vampire, hunter or neutral.

Reproducible on death every time.

### Relevant log output

```bash
[23Apr2022 01:37:01.158] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: MrCurlyFries275 died
[23Apr2022 01:37:04.450] [Server thread/WARN] [de.teamlapen.werewolves.entities.player.werewolf.WerewolfPlayer/]: Cannot get Werewolf player capability. This might break mod functionality.
java.lang.Throwable: null
        at de.teamlapen.werewolves.entities.player.werewolf.WerewolfPlayer.getOpt(WerewolfPlayer.java:89) ~[Werewolves-1.18.2-1.8-0.6.0-alpha+20220419-1840.jar%2373!/:0.6.0-alpha+20220419-1840]
        at de.teamlapen.werewolves.entities.player.ModPlayerEventHandler.playerSize(ModPlayerEventHandler.java:213) ~[Werewolves-1.18.2-1.8-0.6.0-alpha+20220419-1840.jar%2373!/:0.6.0-alpha+20220419-1840]
        at net.minecraftforge.eventbus.ASMEventHandler_439_ModPlayerEventHandler_playerSize_Size.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.event.ForgeEventFactory.getEntitySizeForge(ForgeEventFactory.java:745) ~[forge-1.18.2-40.1.0-universal.jar%2380!/:?]
        at net.minecraft.world.entity.Entity.<init>(Entity.java:252) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:232) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.world.entity.player.Player.<init>(Player.java:171) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:231) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:417) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1281) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2376!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[23Apr2022 01:37:04.453] [Server thread/DEBUG] [de.teamlapen.vampirism.entity.factions.FactionPlayerHandler/FACTIONS]: MrCurlyFries275 has new faction level vampirism:vampire 4
```

### Reproduce steps

1. Die and check console

### Other relevant mods

Mod list for Serverside, which is the only place we are seeing this issue:

Amplified_Nether_v1.1.1.jar
ars_nouveau-1.18.2-2.3.3.jar
AutoRegLib-1.7-53.jar
balm-3.0.2+0.jar
BetterAdvancements-1.18.2-0.1.2.125.jar
cfm-7.0.0-pre29-1.18.2.jar
ChiselsBits-forge-1.18.2-1.2.84-universal.jar
Chunky-1.2.164.jar
CreativeCore_FORGE_v2.6.9_mc1.18.2.jar
curios-forge-1.18.2-5.0.7.0.jar
difficultraids-1.1.1-beta.jar
dimdungeons-1.14.0-forge-1.18.2.jar
DungeonCrawl-1.18.2-2.3.7.jar
elevatorid-1.18.2-1.8.4.jar
engineersdecor-1.18.2-1.1.22-b2.jar
ferritecore-4.2.0-forge.jar
flatbedrock-1.4.2-build.9+mc1.18.2.jar
geckolib-1.18-forge-3.0.15.jar
gravestone-1.18.2-1.0.2.jar
Guide-API-VP-1.18.1-2.2.3.jar
ImmersiveEngineering-1.18.2-8.0.1-147.jar
incontrol-1.18-6.0.6.jar
ironchest-1.18-13.0.7.jar
jei-1.18.2-9.7.0.193.jar
littlelogistics-mc1.18.2-v1.2.3.jar
markdown_manual-1.18.2-forge-1.2.1+59006bb.jar
netherportalfix-forge-1.18-9.0.0.jar
oc2-1.18.2-forge-0.1.7+6a003fc.jar
Patchouli-1.18.2-67.jar
Quark-3.2-349.jar
sedna-1.18.2-forge-1.0.13+7355dbe.jar
StorageDrawers-1.18.2-10.2.0.jar
SuperCircuitMaker2-0.2.3+1.18.2.jar
TKLib-0.0.8+1.18.1.jar
Vampirism-1.18.2-1.8.2-alpha+20220413-2209.jar
Werewolves-1.18.2-1.8-0.6.0-alpha+20220419-1840.jar
wthit-forge-4.8.1.jar

**Comment by Cheaterpaul** [comment]
Don't worry that will break nothing.

The log message will we fixed in the next release

**Comment by phillipinman** [comment]
Thanks for that, ill mark this as closed then if that's all good :)

Also thanks for your work on the mod, loving it.
